import { ValidationReport } from './types';

export const CURATED_QUERIES: ValidationReport[] = [
  {
    id: 'curated_1',
    ideaText: 'Автономный AI-агент для автоматического код-ревью в GitHub Pull Requests с выявлением архитектурных регрессий и генерацией фикс-коммитов',
    targetMarket: 'DevTools & Infra',
    createdAt: Date.now() - 1000 * 60 * 60 * 5, // 5 hours ago
    uniquenessScore: 78,
    verdict: {
      title: 'Перспективная отстройка от статических линтеров',
      description: 'Рынок AI-код-ревью бурно растет, но большинство игроков делают поверхностный линтинг. Глубокий анализ архитектурных контрактов создает устойчивый ров.',
      level: 'promising',
      badgeColor: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/30',
      accentColor: '#10b981',
    },
    metrics: {
      innovation: 82,
      saturation: 48,
      moat: 74,
      cacDifficulty: 52,
      retentionPotential: 88,
    },
    ruthlessCritique: {
      founderBias: 'Иллюзия, что разработчики готовы читать длинные отчеты бота. На деле любой шум приводит к отключению инструмента.',
      switchingBarrier: 'Привычка полагаться исключительно на человеческое ревью внутри команды.',
      retentionPitfall: 'Выгорание от ложных замечаний в срочных hotfix PR.',
      monetizationFlaw: 'Долгий цикл согласования корпоративной безопасности при доступе к приватным репозиториям.',
    },
    similarWebsites: [
      {
        name: 'CodeRabbit',
        url: 'https://coderabbit.ai',
        domain: 'coderabbit.ai',
        stage: 'Series A ($16M)',
        pricingModel: 'Freemium ($15/seat/mo)',
        trafficEstimate: '~1.8M визитов/мес',
        tagline: 'AI-first code reviews that developers actually love',
        whatTheyDo: 'Генерирует сводки PR и комментарии к диффам в GitHub/GitLab.',
        growthChannel: 'GitHub Marketplace PLG',
        blindSpot: 'Слабо понимает кросс-репозиторные зависимости и бизнес-логику домена.',
      },
      {
        name: 'Ellipsis',
        url: 'https://ellipsis.dev',
        domain: 'ellipsis.dev',
        stage: 'Seed ($4M, Y Combinator)',
        pricingModel: 'Usage-based ($20/active dev)',
        trafficEstimate: '~250k визитов/мес',
        tagline: 'Turns code reviews into commits',
        whatTheyDo: 'Не просто комментирует PR, но сам пушит фиксы багов.',
        growthChannel: 'Twitter dev influencers & HackerNews',
        blindSpot: 'Ограниченная поддержка монорепозиториев и кастомных CI пайплайнов.',
      },
      {
        name: 'Sourcery',
        url: 'https://sourcery.ai',
        domain: 'sourcery.ai',
        stage: 'Early Stage ($5M)',
        pricingModel: 'Freemium / Team ($10/mo)',
        trafficEstimate: '~600k визитов/мес',
        tagline: 'Automated refactoring for fast engineering teams',
        whatTheyDo: 'Рефакторинг кода и выявление дубликатов на лету в IDE и PR.',
        growthChannel: 'VS Code Extension Ecosystem',
        blindSpot: 'Фокусируется на стиле кода, а не на системном дизайне.',
      },
    ],
    competitors: [
      {
        name: 'GitHub Copilot Workspace',
        type: 'incumbent',
        description: 'Встроенный в экосистему GitHub AI-инструментарий для работы с issue и PR.',
        strength: 'Встроенная база пользователей и нулевой порог авторизации.',
        vulnerability: 'Медленный темп внедрения узких специализированных правил компаний.',
        estimatedFundingOrReach: 'Microsoft Corp',
      },
    ],
    redFlags: [
      {
        title: 'Усталость разработчиков от "галлюцинаций" в комментариях PR',
        riskLevel: 'high',
        description: 'Если агент оставит хотя бы 2-3 ложных замечания, инженеры отключат бота.',
        mitigationHint: 'Внедрить строгий порог уверенности (confidence score > 90%) перед публикацией комментариев.',
      },
      {
        title: 'Безопасность исходного кода и NDA корпоративных клиентов',
        riskLevel: 'critical',
        description: 'Enterprise-клиенты откажутся слать код во внешние LLM без on-premise или VPC изоляции.',
        mitigationHint: 'Поддержка Self-hosted моделей и сертификации SOC2 / ISO 27001.',
      },
    ],
    blueOceanPivots: [
      {
        title: 'Compliance & Architectural Policy Enforcer',
        expectedUniqueness: 89,
        angle: 'От общего код-ревью к строгому контролю архитектурных стандартов',
        description: 'Фокус не на запятых, а на соблюдении Domain-Driven Design, отсутствии N+1 запросов и изоляции микросервисов.',
        tacticalMove: 'Сделать DSL-правила на естественном языке, которые CTO может сформулировать за 5 минут.',
      },
    ],
    unitEconomics: {
      cacEstimate: '$120–$250 (B2B PLG)',
      expectedLtv: '$1,800–$3,500/год на команду',
      paybackPeriod: '3–4 месяца',
      marginProfile: '78% (с учетом затрат на LLM токены)',
      burnRisk: 'Высокая стоимость инференса при сканировании гигантских PR',
    },
    gtmPlaybook: [
      {
        phase: 'Фаза 1: Open Source & GitHub App',
        channel: 'GitHub Marketplace',
        tacticalAction: 'Бесплатный тариф для публичных open-source репозиториев для виральности.',
        timeline: 'Недели 1–4',
      },
      {
        phase: 'Фаза 2: Direct Outreach CTO',
        channel: 'LinkedIn / Cold Email',
        tacticalAction: 'Анализ публичных PR перспективных стартапов и отправка готового аудита их кодовой базы.',
        timeline: 'Месяцы 2–3',
      },
    ],
    marketSizing: {
      tam: '$12.8B (Global Code Quality & AI DevTools)',
      sam: '$2.4B (Cloud Git Teams)',
      som: '$45M (Первые 500 tech-компаний)',
      averageCheck: '$240/месяц',
    },
    quickTakeaway: 'Сильная гипотеза с четким роудмапом монетизации. Ключевой фактор успеха — нулевой уровень ложных срабатываний (zero-noise PRs).',
    sourceProvider: 'gemini_search',
  },
  {
    id: 'curated_2',
    ideaText: 'B2B AI-симулятор переговоров и тренажер холодных звонков для сейлз-команд с обратной связью в реальном времени',
    targetMarket: 'B2B SaaS',
    createdAt: Date.now() - 1000 * 60 * 60 * 18, // 18 hours ago
    uniquenessScore: 71,
    verdict: {
      title: 'Высокий рыночный спрос при умеренной конкуренции',
      description: 'Онбординг менеджеров по продажам — одна из самых дорогих статей расходов отделов продаж. Голосовой AI сокращает Ramp-up time с 3 месяцев до 2 недель.',
      level: 'promising',
      badgeColor: 'text-sky-400 bg-sky-500/10 border-sky-500/30',
      accentColor: '#38bdf8',
    },
    metrics: {
      innovation: 76,
      saturation: 58,
      moat: 62,
      cacDifficulty: 65,
      retentionPotential: 81,
    },
    ruthlessCritique: {
      founderBias: 'Уверенность, что менеджеры захотят добровольно тренироваться с AI без жесткого KPI от руководства.',
      switchingBarrier: 'Сложность выгрузки скриптов и методологий из голов топовых продавцов.',
      retentionPitfall: 'Снижение использования после прохождения базовых скриптов.',
      monetizationFlaw: 'Высокая стоимость генерации потокового голоса снижает валовую маржу.',
    },
    similarWebsites: [
      {
        name: 'Hyperbound',
        url: 'https://hyperbound.ai',
        domain: 'hyperbound.ai',
        stage: 'Seed ($2.7M)',
        pricingModel: 'Per Rep ($99/seat/mo)',
        trafficEstimate: '~180k визитов/мес',
        tagline: 'Simulated sales roleplay with AI buyers',
        whatTheyDo: 'Голосовые симуляции звонков с капризными B2B-покупателями.',
        growthChannel: 'Sales LinkedIn influencers',
        blindSpot: 'Слабая локализация на языки помимо английского.',
      },
      {
        name: 'Second Nature AI',
        url: 'https://secondnature.ai',
        domain: 'secondnature.ai',
        stage: 'Series A ($12.5M)',
        pricingModel: 'Enterprise Annual Contracts',
        trafficEstimate: '~120k визитов/мес',
        tagline: 'AI-powered sales coaching at scale',
        whatTheyDo: 'Виртуальный тренер Дженни для сертификации сейлзов крупных корпораций.',
        growthChannel: 'Enterprise Sales Directors',
        blindSpot: 'Сложный энтерпрайзный цикл внедрения (2–4 месяца).',
      },
    ],
    competitors: [
      {
        name: 'Gong / Chorus',
        type: 'incumbent',
        description: 'Платформы Revenue Intelligence, анализирующие реальные звонки.',
        strength: 'Огромный архив реальных транскриптов звонков для обучения.',
        vulnerability: 'Анализируют звонки постфактум, но не дают тренироваться до первого контакта с клиентом.',
        estimatedFundingOrReach: 'Gong ($580M raised, $7B valuation)',
      },
    ],
    redFlags: [
      {
        title: 'Задержка голосового ответа (Voice Latency)',
        riskLevel: 'high',
        description: 'Если пауза перед ответом симулятора превышает 600-800мс, реалистичность диалога рушится.',
        mitigationHint: 'Использование ultra-low latency WebSockets и моделей типа Cartesia / ElevenLabs Turbo.',
      },
    ],
    blueOceanPivots: [
      {
        title: 'Objection-Handling Speed Run',
        expectedUniqueness: 84,
        angle: 'Геймифицированный тренажер работы с возражениями («Дорого», «Уже работаем с другими»)',
        description: 'Микро-тренировки по 5 минут в начале рабочего дня с таблицей лидеров среди коллег.',
        tacticalMove: 'Встроить интеграцию с CRM: генерировать кейс симуляции на основе реальной сорванной сделки.',
      },
    ],
    unitEconomics: {
      cacEstimate: '$450–$900',
      expectedLtv: '$3,600/год',
      paybackPeriod: '3 месяца',
      marginProfile: '72%',
      burnRisk: 'Расходы на Realtime Voice API',
    },
    gtmPlaybook: [
      {
        phase: 'Пилот с агентствами телемаркетинга',
        channel: 'Cold Outreach',
        tacticalAction: 'Предложить 10 бесплатным колл-центрам протестировать сокращение отсева стажеров.',
        timeline: 'Месяц 1',
      },
    ],
    marketSizing: {
      tam: '$7.5B (Sales Training & Enablement)',
      sam: '$1.8B',
      som: '$25M',
      averageCheck: '$1,200/месяц на команду',
    },
    quickTakeaway: 'Высокая ценность для Head of Sales. Окупаемость подтверждается экономией времени старших тимлидов на коучинг новичков.',
    sourceProvider: 'gemini_search',
  },
  {
    id: 'curated_3',
    ideaText: 'P2P-маркетплейс для аренды профессиональной фото- и кинотехники с депозитом на смарт-контракте и мгновенной экспресс-страховкой',
    targetMarket: 'Marketplace / P2P',
    createdAt: Date.now() - 1000 * 60 * 60 * 36, // 36 hours ago
    uniquenessScore: 44,
    verdict: {
      title: 'Перенасыщенный и капиталоемкий рынок с высокими рисками фрода',
      description: 'Проблема простоя дорогого оборудования реальна, но модель P2P аренды страдает от колоссального риска кражи и поломки техники.',
      level: 'crowded',
      badgeColor: 'text-rose-400 bg-rose-500/10 border-rose-500/30',
      accentColor: '#f43f5e',
    },
    metrics: {
      innovation: 45,
      saturation: 84,
      moat: 32,
      cacDifficulty: 88,
      retentionPotential: 42,
    },
    ruthlessCritique: {
      founderBias: 'Вера в то, что смарт-контракты решают проблему физического повреждения или кражи оборудования.',
      switchingBarrier: 'Личные связи операторов со знакомыми офлайн-прокатами с гибкой отсрочкой платежей.',
      retentionPitfall: 'Сезонность съемок и нерегулярность заказов у фрилансеров.',
      monetizationFlaw: 'Комиссия маркетплейса съедается расходами на проверку юристов и урегулирование убытков.',
    },
    similarWebsites: [
      {
        name: 'ShareGrid',
        url: 'https://sharegrid.com',
        domain: 'sharegrid.com',
        stage: 'Acquired by Backstage',
        pricingModel: '15-20% транзакционная комиссия',
        trafficEstimate: '~1.1M визитов/мес',
        tagline: 'The largest camera sharing community',
        whatTheyDo: 'Аренда кинокамер, оптики и света между продакшенами в США.',
        growthChannel: 'Community word-of-mouth & film schools',
        blindSpot: 'Длительная ручная верификация личности (до 48 часов).',
      },
      {
        name: 'Fat Llama',
        url: 'https://fatllama.com',
        domain: 'fatllama.com',
        stage: 'Acquired by Hygglo ($41M)',
        pricingModel: 'Commission 25% total',
        trafficEstimate: '~950k визитов/мес',
        tagline: 'Rent almost anything from people nearby',
        whatTheyDo: 'Универсальный маркетплейс аренды любых вещей, где фототехника — топ-категория.',
        growthChannel: 'SEO & PR campaigns',
        blindSpot: 'Высокие франшизы страховых выплат при повреждении оптики.',
      },
    ],
    competitors: [
      {
        name: 'Локальные профессиональные ренталы (Lensrentals / Rentaphoto)',
        type: 'incumbent',
        description: 'Офлайн-прокаты с собственным проверенным парком техники и штатом инженеров.',
        strength: '100% гарантия юстировки объективов и чистоты матриц перед съемкой.',
        vulnerability: 'Ограниченная география и закрытие складов по выходным.',
        estimatedFundingOrReach: 'Локальные монополисты',
      },
    ],
    redFlags: [
      {
        title: 'Уязвимость перед мошенничеством по поддельным паспортам',
        riskLevel: 'critical',
        description: 'Камеры RED / Sony FX6 стоимостью $6,000+ часто берут в аренду по дроп-документам с целью сбыта на черном рынке.',
        mitigationHint: 'Требовать биометрический Liveness-check и hardware-трекеры в чемоданах оборудования.',
      },
    ],
    blueOceanPivots: [
      {
        title: 'Прокат студийного пространства и света «под ключ» с оператором',
        expectedUniqueness: 72,
        angle: 'От аренды железа на руки к букингу съемочных сетов с оборудованием на месте',
        description: 'Техника не покидает охраняемую студию, что снижает риск кражи до нуля и снимает необходимость гигантских депозитов.',
        tacticalMove: 'Партнерство с пустующими фотостудиями в будние дни.',
      },
    ],
    unitEconomics: {
      cacEstimate: '$85 на арендатора',
      expectedLtv: '$190',
      paybackPeriod: '8–12 месяцев',
      marginProfile: '18% чистой комиссии (после вычета страховок)',
      burnRisk: 'Высокий риск судебных издержек при спорных поломках',
    },
    gtmPlaybook: [
      {
        phase: 'Запуск в одном городе',
        channel: 'Telegram-каналы операторов',
        tacticalAction: 'Привлечь первые 30 топовых комплектов техники у проверенных знакомых операторов.',
        timeline: 'Месяцы 1–2',
      },
    ],
    marketSizing: {
      tam: '$3.2B (Photo & Cinema Equipment Rental)',
      sam: '$400M (P2P Share)',
      som: '$8M',
      averageCheck: '$90/транзакция',
    },
    quickTakeaway: 'Крайне тяжелая операционная модель с высокими рисками краж и низким LTV. Рекомендуется трансформировать модель в b2b-агрегатор студий.',
    sourceProvider: 'gemini_search',
  },
  {
    id: 'curated_4',
    ideaText: 'AI-копилот для врачей общей практики: транскрибация приема пациента, генерация медкарты в МИС и проверка лекарственных взаимодействий',
    targetMarket: 'HealthTech & Med',
    createdAt: Date.now() - 1000 * 60 * 60 * 50, // 2 days ago
    uniquenessScore: 83,
    verdict: {
      title: 'Голубой океан в СНГ при буме инвестиций в США',
      description: 'Врачи тратят до 40% рабочего времени на заполнение карточек. Освобождение этого ресурса прямо увеличивает выручку клиники на 20-30%.',
      level: 'blue_ocean',
      badgeColor: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/30',
      accentColor: '#10b981',
    },
    metrics: {
      innovation: 89,
      saturation: 35,
      moat: 86,
      cacDifficulty: 78,
      retentionPotential: 94,
    },
    ruthlessCritique: {
      founderBias: 'Недооценка консерватизма врачей и сопротивления внедрению любого софта, вмешивающегося в прием.',
      switchingBarrier: 'Связка клиники с существующей МИС (1С, МедИнфо) с закрытыми API.',
      retentionPitfall: 'Штрафы от Минздрава в случае малейшей неточности в протоколе осмотра.',
      monetizationFlaw: 'Длительные тендерные процедуры и долгий цикл принятия решений.',
    },
    similarWebsites: [
      {
        name: 'Abridge',
        url: 'https://abridge.com',
        domain: 'abridge.com',
        stage: 'Series C ($150M raised, $850M valuation)',
        pricingModel: 'Enterprise hospital subscription',
        trafficEstimate: '~400k визитов/мес',
        tagline: 'AI ambient listening for clinical documentation',
        whatTheyDo: 'Слушает разговор врача и пациента, формируя структурированные заметки в Epic/Cerner.',
        growthChannel: 'Hospital Enterprise Partnerships',
        blindSpot: 'Дорогие многомиллионные контракты, недоступные для частных небольших клиник.',
      },
      {
        name: 'Suki AI',
        url: 'https://suki.ai',
        domain: 'suki.ai',
        stage: 'Series D ($70M)',
        pricingModel: '$399/клиницист/мес',
        trafficEstimate: '~190k визитов/мес',
        tagline: 'Voice-first AI assistant for healthcare',
        whatTheyDo: 'Голосовой ассистент для заполнения рецептов и кодирования диагнозов по МКБ.',
        growthChannel: 'Direct-to-physician and medical associations',
        blindSpot: 'Фокус только на американской системе кодирования ICD-10 и CPT.',
      },
    ],
    competitors: [
      {
        name: 'Nuance DAX Copilot (Microsoft)',
        type: 'incumbent',
        description: 'Лидер медицинского распознавания речи, купленный Microsoft за $19.7B.',
        strength: 'Глубокая интеграция во все крупнейшие больничные сети США.',
        vulnerability: 'Медленный интерфейс и отсутствие гибкости под региональные протоколы.',
        estimatedFundingOrReach: 'Microsoft Healthcare Division',
      },
    ],
    redFlags: [
      {
        title: 'Медицинская тайна и врачебная ответственность (HIPAA / ФЗ-152)',
        riskLevel: 'critical',
        description: 'Аудиозапись разговора с пациентом требует строгого согласия и шифрования на серверах внутри юрисдикции.',
        mitigationHint: 'Обработка аудио на локальном девайсе клиники или в сертифицированном медицинском облаке.',
      },
    ],
    blueOceanPivots: [
      {
        title: 'Интеграция с локальными сетями частных стоматологий и косметологий',
        expectedUniqueness: 92,
        angle: 'Старт не с тяжелых государственных больниц, а с частной коммерческой медицины',
        description: 'В частных клиниках решения принимают владельцы за 1 день, а средний чек пациента в 5 раз выше.',
        tacticalMove: 'Готовый плагин для 1С:Медицина и МедЛог.',
      },
    ],
    unitEconomics: {
      cacEstimate: '$800–$1,500 на клинику',
      expectedLtv: '$12,000+ (отток < 3% в год)',
      paybackPeriod: '2–3 месяца',
      marginProfile: '84%',
      burnRisk: 'Сертификация и юридические заключения',
    },
    gtmPlaybook: [
      {
        phase: 'Пилот с 3 частными сетями',
        channel: 'Личный нетворк главврачей',
        tacticalAction: 'Бесплатное внедрение на 2 недели в обмен на публичный видеоотзыв главврача.',
        timeline: 'Месяц 1',
      },
    ],
    marketSizing: {
      tam: '$18.5B (Global Clinical Documentation AI)',
      sam: '$2.1B (Private Clinics in Target Region)',
      som: '$35M',
      averageCheck: '$450/месяц на филиал клиники',
    },
    quickTakeaway: 'Один из самых сильных венчурных трендов десятилетия. Огромный LTV и устойчивый барьер перехода (высокий Moat).',
    sourceProvider: 'gemini_search',
  },
  {
    id: 'curated_5',
    ideaText: 'Платформа автоматического микро-SEO: AI находит низкоконкурентные поисковые запросы и автоматически генерирует индексируемые лендинги',
    targetMarket: 'Consumer Mobile',
    createdAt: Date.now() - 1000 * 60 * 60 * 72, // 3 days ago
    uniquenessScore: 62,
    verdict: {
      title: 'Инкрементальный продукт с высокими рисками бана от Google Search',
      description: 'Программное SEO работает, однако последние апдейты поисковых систем активно пенализируют сгенерированный без экспертизы AI-контент.',
      level: 'incremental',
      badgeColor: 'text-amber-400 bg-amber-500/10 border-amber-500/30',
      accentColor: '#f59e0b',
    },
    metrics: {
      innovation: 60,
      saturation: 72,
      moat: 41,
      cacDifficulty: 55,
      retentionPotential: 58,
    },
    ruthlessCritique: {
      founderBias: 'Иллюзия «пассивного трафика»: поисковые алгоритмы постоянно меняются, требуя регулярной ручной доработки контента.',
      switchingBarrier: 'Собственные кастомные скрипты вебмастеров или CMS с плагинами Yoast/RankMath.',
      retentionPitfall: 'Массовый отток пользователей после первого же апдейта Google Search.',
      monetizationFlaw: 'Низкий LTV соло-мейкеров, которые отменяют подписку после генерации страниц.',
    },
    similarWebsites: [
      {
        name: 'Programmatic SEO Tools',
        url: 'https://untitledui.com',
        domain: 'untitledui.com',
        stage: 'Bootstrapped',
        pricingModel: 'One-time payment $129',
        trafficEstimate: '~350k визитов/мес',
        tagline: 'Scale organic traffic with programmatic pages',
        whatTheyDo: 'Базы данных и шаблоны для массовой генерации посадочных страниц.',
        growthChannel: 'Twitter SEO community',
        blindSpot: 'Нет живой интеграции с LLM для обновления контента.',
      },
      {
        name: 'Letterdrop',
        url: 'https://letterdrop.com',
        domain: 'letterdrop.com',
        stage: 'Seed ($3.2M, Y Combinator)',
        pricingModel: '$450/mo B2B',
        trafficEstimate: '~210k визитов/мес',
        tagline: 'First-party SEO and automated content distribution',
        whatTheyDo: 'SEO-инструмент для создания экспертного контента на основе внутренних данных компании.',
        growthChannel: 'LinkedIn Content & Podcasts',
        blindSpot: 'Высокая цена, недоступная для инди-хакеров и соло-фаундеров.',
      },
    ],
    competitors: [
      {
        name: 'Semrush / Ahrefs AI writing assistants',
        type: 'incumbent',
        description: 'Крупнейшие базы поисковых данных с недавно встроенными AI-моделями.',
        strength: 'Точнейшие данные по частотности запросов и обратным ссылкам.',
        vulnerability: 'Громоздкие интерфейсы, требующие часов ручной работы SEO-специалиста.',
        estimatedFundingOrReach: 'Public NASDAQ Company',
      },
    ],
    redFlags: [
      {
        title: 'Google Helpful Content Update (HCU)',
        riskLevel: 'critical',
        description: 'Массовая генерация страниц под Long-Tail запросы часто приводит к полному исключению домена из поискового индекса.',
        mitigationHint: 'Добавлять уникальные данные из реальных API, калькуляторы и пользовательские отзывы на каждую страницу.',
      },
    ],
    blueOceanPivots: [
      {
        title: 'Programmatic Tools & Calculators Generator',
        expectedUniqueness: 82,
        angle: 'От генерации текстовых статей к генерации интерактивных мини-калькуляторов',
        description: 'Google ранжирует интерактивные инструменты в 10 раз лучше, чем обычные AI-тексты (высокий time-on-page).',
        tacticalMove: 'Автогенерация React-виджетов и встраиваемых калькуляторов под каждый запрос.',
      },
    ],
    unitEconomics: {
      cacEstimate: '$60 (через собственное SEO)',
      expectedLtv: '$480',
      paybackPeriod: '2 месяца',
      marginProfile: '85%',
      burnRisk: 'Внезапное падение органического трафика после апдейта поисковиков',
    },
    gtmPlaybook: [
      {
        phase: 'Публичный запуск кейса «От 0 до 100k визитов»',
        channel: 'HackerNews / ProductHunt',
        tacticalAction: 'Опубликовать реальный кейс продвижения домена с открытой Google Search Console.',
        timeline: 'Недели 1–2',
      },
    ],
    marketSizing: {
      tam: '$68B (Global SEO Services)',
      sam: '$4.5B (SaaS & Micro-tools)',
      som: '$15M',
      averageCheck: '$49/месяц',
    },
    quickTakeaway: 'Интересный инструмент для инди-мейкеров, но подвержен регуляторным рискам поисковых алгоритмов. Устойчив только при создании реальной интерактивной ценности.',
    sourceProvider: 'gemini_search',
  },
];
